### PR TITLE
Fix and extend README

### PR DESCRIPTION
**Pull request by real-or-random**
At least that is what worked for me.

### CODE REVIEW

**Comment by kerel-fs** [comment]
Hi! I'm starting aw-server via systemd, so this can't be used to start the session-dependent aw-watcher-gnome like you did here. Instead, I added the following xdg desktop file to enable autostart of aw-watcher. service:
```
[Desktop Entry]
Name=ActivityWatch Gnome Watcher
GenericName=Time-tracking application watcher for GNOME
Exec=/opt/aw-watcher-gnome/aw-watcher-gnome
Hidden=false
StartupNotify=true
Terminal=false
Type=Application
X-GNOME-Autostart-enabled=true
Version=1.0
Icon=activitywatch
Categories=Utility;
```

Just copy this to `~/.config/autostart/aw-watcher-gnome.desktop` to enable it.

[ideially I would create a PR on the upstream docs to document systemd usage for aw-server as well, but for now this comment alone must do].

**Comment by flexagoon** [comment]
@real-or-random @kerel-fs

I actually use systemd to start aw-server and aw-watcher-gnome as well. I use two separate systemd services for them, with one having a dependency on the other. I think I'll just commit the ones I use to this repo and add an instruction to the readme.

**Comment by real-or-random** [comment]
Sounds good, I also use systemd. But note that my comment doesn't only extend the README, it also fixes the "replace" sentence. (`aw-server` shouldn't be replaced.` So I think this should be merged, even if the systemd files are added. But I can split the commit if you insist.

---

These are my files by the way, feel free to steal.

cat aw-server.service: 
```
[Unit]
Description=ActivityWatcher Watcher Server
After=graphical-session.target

[Service]
ExecStart=/opt/activitywatch/aw-server/aw-server
# ExecStart=/opt/activitywatch/aw-server-rust/aw-server-rust

[Install]
WantedBy=graphical-session.target
```

aw-watcher-gnome.service:
``` 
[Unit]
Description=ActivityWatcher Watcher for GNOME
After=org.gnome.Shell@wayland.service
Requires=org.gnome.Shell@wayland.service
Wants=aw-server.service

[Service]
ExecStart=/opt/activitywatch/aw-watcher-gnome/aw-watcher-gnome

[Install]
WantedBy=graphical-session.target
```

Not sure if they're optimal, but they work for me so far.

**Comment by flexagoon** [comment]
There is a systemd autostart method now!

**Pull request closed without merging**
